#!/usr/bin/env python3
"""Clean-room WSPR Type-1 reference encoder (from the public G4JNT algorithm).
Generates golden channel symbols and a 4-FSK WAV for decoder round-trip checking.
Not part of the shipped firmware."""
import sys, struct, math

SYNC = [  # 162-bit WSPR sync vector
 1,1,0,0,0,0,0,0,1,0,0,0,1,1,1,0,0,0,1,0,0,1,0,1,1,1,1,0,0,0,
 0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,1,0,0,0,1,
 1,0,1,0,0,0,0,1,1,0,1,0,1,0,1,0,1,0,0,1,0,0,1,0,1,1,0,0,0,1,
 1,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,1,1,0,1,1,0,0,1,1,
 0,1,0,0,0,1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,0,0,0,0,0,0,1,1,0,
 1,0,1,1,0,0,0,1,1,0,0,0]

def cval(c):  # '0'-'9'->0..9, 'A'-'Z'->10..35, ' '->36
    if '0' <= c <= '9': return ord(c) - ord('0')
    if 'A' <= c <= 'Z': return ord(c) - ord('A') + 10
    if c == ' ': return 36
    raise ValueError("bad char %r" % c)

def normalize_call(call):
    up = call.upper()
    if '/' in up or not (3 <= len(up) <= 6):
        raise ValueError("not Type-1 callsign: %r" % call)
    shift = 0
    if not up[2].isdigit():
        if len(up) >= 2 and up[1].isdigit():
            shift = 1
        else:
            raise ValueError("no positionable digit: %r" % call)
    field = [' '] * 6
    for i, ch in enumerate(up):
        if shift + i >= 6: raise ValueError("too long after shift: %r" % call)
        field[shift + i] = ch
    if not field[2].isdigit(): raise ValueError("digit not in col 3: %r" % call)
    return ''.join(field)

def pack_call(field):
    n = cval(field[0])
    n = n * 36 + cval(field[1])
    n = n * 10 + (ord(field[2]) - ord('0'))
    n = n * 27 + (cval(field[3]) - 10)
    n = n * 27 + (cval(field[4]) - 10)
    n = n * 27 + (cval(field[5]) - 10)
    return n  # 28 bits

def pack_grid_power(grid, dbm):
    g = grid.upper()
    if len(g) != 4: raise ValueError("grid must be 4 chars")
    g1, g2 = ord(g[0]) - ord('A'), ord(g[1]) - ord('A')
    g3, g4 = ord(g[2]) - ord('0'), ord(g[3]) - ord('0')
    if not (0 <= g1 <= 17 and 0 <= g2 <= 17 and 0 <= g3 <= 9 and 0 <= g4 <= 9):
        raise ValueError("bad grid %r" % grid)
    if not (0 <= dbm <= 60 and dbm % 10 in (0, 3, 7)):
        raise ValueError("bad dBm %r" % dbm)
    m1 = (179 - 10 * g1 - g3) * 180 + 10 * g2 + g4
    return m1 * 128 + dbm + 64  # 22 bits

def parity(x):
    return bin(x).count('1') & 1

def encode_symbols(call, grid, dbm):
    n = pack_call(normalize_call(call))
    m = pack_grid_power(grid, dbm)
    bits = [(n >> (27 - i)) & 1 for i in range(28)] + \
           [(m >> (21 - i)) & 1 for i in range(22)]
    # convolutional K=32, r=1/2 over 50 data + 31 tail bits
    reg = 0; enc = []
    for i in range(81):
        b = bits[i] if i < 50 else 0
        reg = ((reg << 1) | b) & 0xFFFFFFFF
        enc.append(parity(reg & 0xf2d05351))
        enc.append(parity(reg & 0xe4613c47))
    # bit-reversal interleave
    inter = [0] * 162
    i = 0
    for p in range(256):
        j = int('{:08b}'.format(p)[::-1], 2)
        if j < 162:
            inter[j] = enc[i]; i += 1
        if i >= 162: break
    # merge with sync -> 4-FSK symbols
    return [SYNC[k] + 2 * inter[k] for k in range(162)]

def write_wav(symbols, path, fs=12000, base_hz=1500.0):
    spacing = 12000.0 / 8192.0
    sps = fs * 8192.0 / 12000.0
    total = int(round(sps * len(symbols)))
    phase = 0.0; data = bytearray()
    for s in range(total):
        sym = symbols[min(int(s / sps), len(symbols) - 1)]
        f = base_hz + spacing * sym
        phase += 2 * math.pi * f / fs
        data += struct.pack('<h', int(0.5 * 32767 * math.sin(phase)))
    with open(path, 'wb') as w:
        n = len(data)
        w.write(b'RIFF'); w.write(struct.pack('<I', 36 + n)); w.write(b'WAVE')
        w.write(b'fmt '); w.write(struct.pack('<IHHIIHH', 16, 1, 1, fs, fs * 2, 2, 16))
        w.write(b'data'); w.write(struct.pack('<I', n)); w.write(data)

if __name__ == '__main__':
    cases = [("K1ABC", "FN42", 37), ("G4JNT", "IO90", 27)]
    print("// Generated by tools/wspr_ref.py -- do not edit by hand.")
    print("#pragma once")
    print("#include <stdint.h>")
    print("typedef struct { const char* call; const char* grid; int dbm;")
    print("                 uint8_t sym[162]; } wspr_golden_t;")
    print("static const wspr_golden_t WSPR_GOLDEN[] = {")
    for call, grid, dbm in cases:
        syms = encode_symbols(call, grid, dbm)
        body = ','.join(str(x) for x in syms)
        print('  {"%s","%s",%d,{%s}},' % (call, grid, dbm, body))
    print("};")
    if len(sys.argv) > 1 and sys.argv[1] == '--wav':
        write_wav(encode_symbols("K1ABC", "FN42", 37), "k1abc_fn42_37.wav")
        sys.stderr.write("wrote k1abc_fn42_37.wav\n")
